language: generic
services:
  - docker
env:
  - BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
before_install: |
  cd $TRAVIS_BUILD_DIR \
  && git clone https://github.com/bbernhard/imagemonkey-core imagemonkey-core \
  && cd $TRAVIS_BUILD_DIR/imagemonkey-core \
  && echo "Creating data directory" \
  && mkdir -p $TRAVIS_BUILD_DIR/imagemonkey-core/data/donations \
  && mkdir -p $TRAVIS_BUILD_DIR/imagemonkey-core/data/quarantine \
  && mkdir -p $TRAVIS_BUILD_DIR/imagemonkey-core/data/unverified_donations \
  && docker-compose -f env/docker/docker-compose.travis.yml build
script:
  cd $TRAVIS_BUILD_DIR/imagemonkey-core && docker-compose -f env/docker/docker-compose.travis.yml up --abort-on-container-exit --exit-code-from testing
